apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: openai-opt
  namespace: gloo-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: openai
  options:
    ai:
      rag:
        datastore:
          postgres:
            connectionString: postgresql+psycopg://gloo:gloo@vector-db.gloo-system.svc.cluster.local:5432/gloo
            collectionName: default
        embedding:
          openai:
            authToken:
              secretRef:
                name: openai-secret
                namespace: gloo-system
    stagedTransformations:
      early:
        requestTransforms:
        - requestTransformation:
            logRequestResponseInfo: true
            transformationTemplate:
              headers:
                x-early-request-header: 
                  text: "early"
      regular:
        requestTransforms:
        - requestTransformation:
            # ddoyle: Just want to log request and response.
            logRequestResponseInfo: true
            transformationTemplate:
              headers:
                x-regular-request-header: 
                  text: "regular"