apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
  name: mistralai
  namespace: gloo-system
spec:
  ai:
    mistral:
      authToken:
        secretRef:
          name: mistralai-secret
          namespace: gloo-system