apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
  name: openai
  namespace: gloo-system
spec:
  ai:
    openai:
      customHost:
        host: model-failover.gloo-system.svc.cluster.local
        port: 80
      authToken:
        secretRef:
          name: openai-secret
          namespace: gloo-system